cloud:
  aws:
    credentials:
      access-key: AXXXXXXXXXXX
      secret-key: kXXXXXXXXXXXXXXXX
    region:
      static: ap-south-1
    stack:
      auto: false
    bucket:
      name: netcracker-hackerearth

server:
  port: 5000
